default_env: &default
  adapter: postgresql
  encoding: unicode
  database: counting_stars
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

production:
  <<: *default
  host: dpg-ck961av0vg2c738a9rvg-a
  database: s_original_hh66
  username: s_original_hh66_user
  password: ROHboYu9yhwSnW5FK8oqf3J8xoPbyVwF